### PR TITLE
Add filenames for some new images

### PR DESCRIPTION
**Pull request by breville**
The images were added in https://github.com/code-dot-org/ml-playground/pull/134.

### CODE REVIEW

**Review by made-line — COMMENTED** [review]
Did those images work on your end? Here's what I see:

Screen Shot 2021-04-02 at 7 27 41 PM

**Comment by breville** [comment]
@made-line Please try restarting your server.

**Comment by made-line** [comment]
Per our Slack discussion, running `grunt postbuild` fixed it on my end. Thank you!

**Review by made-line — APPROVED** [review]

**Review by Erin007 — APPROVED** [review]

**Comment by Erin007** [comment]
@dancodedotorg Is the plan to keep (toy) in the name for the in-house created datasets? Not a big deal, just wondering if it will be useful or confusing for students.

**Comment by dancodedotorg** [comment]
@Erin007 That's a good point - thanks for raising it. I think we're at the point where we should get rid of the toy distinction in the name. Maybe something easy to add to this PR?

**Pull request merged**
